[package]
name = "error_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.4"
futures = "0.3.25"
ic-cdk = "0.6.8"
ic-cdk-macros = "0.6.8"
